[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
data-encoding.workspace = true
redis.workspace = true
ring.workspace = true
sqlx.workspace = true
uuid.workspace = true
