[package]
name = "store"
version = "0.1.0"
edition = "2021"

[lib]
name = "store"
path = "./src/lib.rs"

[dependencies]
common.workspace = true

anyhow.workspace = true
csv.workspace = true
redis.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
